# 每个条目就是一个来源（URL 或本地路径），并声明要合并到哪个 label
# 同一个 label 下的多个来源将按顺序合并，并去重
sources:
  - label: "China"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/115/115.list"
  - label: "China"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/12306/12306.list"
  - label: "China"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AliPay/AliPay.list"
  - label: "China"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/BOC/BOC.list"
  - label: "China"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/BiliBili/BiliBili.list"
  - label: "China"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/CMB/CMB.list"
  - label: "China"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/DouYin/DouYin.list"
  - label: "China"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/UnionPay/UnionPay.list"
  - label: "China"
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/WeChat/WeChat.list"

# 可选的全局开关
options:
  sort: false                # 是否对结果排序（默认 false：保持合并顺序）
  deduplicate: true          # 是否去重（默认 true，保持首次出现的顺序）
  normalize_whitespace: true # 规整空白字符
  fail_on_missing: false     # 某个来源 404/路径不存在时是否报错失败（默认 false：跳过并告警）
  delete_orphan_outputs: true # 清理 output 目录里已无对应 label 的历史输出文件（默认 true）

