name: Merge Surge Rules

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch: {}
  push:
    paths:
      - "Config/rule-sources.yaml"
      - "Scripts/merge_rules.py"
      - ".github/workflows/merge-surge-rules.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pyyaml

      - name: Merge Rules
        run: |
          python3 Scripts/merge_rules.py

      - name: Commit & Push if changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -n "$(git status --porcelain Rule)" ]; then
            git add Rule
            git commit -m "chore: update merged Surge lists [skip ci]"
            BRANCH=$(git branch --show-current)
            git push "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git" "$BRANCH"
          else
            echo "No changes in Rule/"
          fi

      - name: Upload artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surge-merged-lists
          path: Rule/*.list
